// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABR57XxRkAjSAfRufLH8pAD-9-6z-71sY',
    appId: '1:830961551666:web:254d131b905cfe0424ef2b',
    messagingSenderId: '830961551666',
    projectId: 'sweet-chat-vf',
    authDomain: 'sweet-chat-vf.firebaseapp.com',
    storageBucket: 'sweet-chat-vf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqpv0hk8tvy3W8Qr1hCvl66IJkDO_VXuo',
    appId: '1:830961551666:android:a15b674b2c4f347c24ef2b',
    messagingSenderId: '830961551666',
    projectId: 'sweet-chat-vf',
    storageBucket: 'sweet-chat-vf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVFze5xOpiTYxNaMsQbg-8GzDw0DF8_U',
    appId: '1:830961551666:ios:3106529c8eba43bd24ef2b',
    messagingSenderId: '830961551666',
    projectId: 'sweet-chat-vf',
    storageBucket: 'sweet-chat-vf.firebasestorage.app',
    iosBundleId: 'com.example.sweetChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVFze5xOpiTYxNaMsQbg-8GzDw0DF8_U',
    appId: '1:830961551666:ios:3106529c8eba43bd24ef2b',
    messagingSenderId: '830961551666',
    projectId: 'sweet-chat-vf',
    storageBucket: 'sweet-chat-vf.firebasestorage.app',
    iosBundleId: 'com.example.sweetChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABR57XxRkAjSAfRufLH8pAD-9-6z-71sY',
    appId: '1:830961551666:web:47f4251ca02ebac024ef2b',
    messagingSenderId: '830961551666',
    projectId: 'sweet-chat-vf',
    authDomain: 'sweet-chat-vf.firebaseapp.com',
    storageBucket: 'sweet-chat-vf.firebasestorage.app',
  );
}
